### ISSUE TITLE
Ansible-galaxy requirements.yml error

### ISSUE THREAD

**Issue by bendata61** [MayfieldRoboticsPublic/ros-webrtc#74]
There seems to be an error running requirements.yml as webrtc git could not be found. A username and password is prompted.

```
[WARNING]: - webrtc was NOT installed successfully: - command git clone https://github.com/mayfieldrobotics/ansible-webrtc.git
webrtc failed in directory /tmp/tmpbnIYbw (rc=128)

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

**Comment by po1** [comment]
Yes, that repository seem to have been deleted some time in the past. It was used to provide the `webrtc` ansible role, which needs to be replaced.
If you ever have success doing that, a PR would be much appreciated :)
