### ISSUE TITLE
ERROR! the role 'webrtc' was not found

### ISSUE THREAD

**Issue by doisyg** [MayfieldRoboticsPublic/ros-webrtc#83]
Hello,
I wanted to try ros-webrtc but can't manage to go beyond the step:
`~/code/ros-webrtc/test/provision$ ansible-playbook -i 'localhost,' -c local -K dev.yml`

I get
```
ERROR! the role 'webrtc' was not found in /*/ros-webrtc/test/provision/roles:/*/ros-webrtc/test/provision:./roles

The error appears to have been in '/*/ros-webrtc/test/provision/dev.yml': line 19, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  - nodejs
  - {role: webrtc, become: yes}
    ^ here
```

Maybe I miss something obvious, this is the first time I am using ansible.

**Comment by po1** [comment]
I believe that role was provided by the `ansible-webrtc` repository that does not seem to exist anymore. See #74. It needs to be replaced. Fetching a binary package from a public source and installing it should work and be simple enough.

**Comment by doisyg** [comment]
Thanks for your answer. I never used ansible before. Could you elaborate a bit more on that?

**Comment by doisyg** [comment]
@po1 Going back on this, I tried to install precompiled library of webrtc but still cannot manage to build ros_webrtc. I think it has to do with using a previous version of webrtc. Which version (branch number) is used here?

**Comment by doisyg** [comment]
@po1 , still failing at this step:
`~/code/ros-webrtc/test/provision$ ansible-playbook -i 'localhost,' -c local -K dev.yml`

Can't get the package libjsoncpp0:
```

TASK [webrtc : install tools via apt] ******************************************
failed: [localhost] => (item=[u'libjsoncpp0', u'libjsoncpp-dev', u'libjingle555cfe9', u'libjingle555cfe9-dev']) => {"failed": true, "item": ["libjsoncpp0", "libjsoncpp-dev", "libjingle555cfe9", "libjingle555cfe9-dev"], "msg": "No package matching 'libjsoncpp0' is available"}

```

**Comment by freddie-ai** [comment]
@doisyg Did you find a workaround/fix for this? Thanks
